### ISSUE TITLE
Issue with using Godot’s memory manager in an independent C++ project

### ISSUE THREAD

**Issue by FashGek** [migueldeicaza/libgodot#4]
### Godot version

3.5

### System information

windows 10 , windwos native app

### Issue description

Hello,
I am currently try to embed the godot in qt , thanks for your greate work. 
the first step I compile this code to a lib & dll, and I try to link this lib&dll using another indepent c++ windows appliation, but I got error 

![2捕获](https://github.com/migueldeicaza/libgodot/assets/2861035/7f9ea102-cccb-4e06-8314-26f1a3107e66)

I got the link error, when memnew(Node2D), cannot link Memeory::alloc_static, I am very sure alread link the lib, beacause it can show the godot window,

whish your reply. 
theank your work

### Steps to reproduce

......

### Minimal reproduction project

...

**Comment by migueldeicaza** [comment]
Libgodot is a fork of 4.0, and beyond its use in SwiftGodot, I can not do much more.
